Repository grufelous/Hacktoberfest-2019, pull requests merged in 2019-10, with the labels that each got.

#5 Added BubbleSort
  DSA/algorithms/Sorting/Java/BubbleSort.java
Labels: hacktoberfest

#7 Added Range Minimum Query Using Segment Trees
  problems/Intermediate/Range_Minimum_Query.md
  problems/Range_Minimum_Query/CPP/RMQST.cpp
Labels: good first issue, hacktoberfest

#10 KMP
  DSA/algorithms/KMP/C++/kmp.cpp
Labels: hacktoberfest

#8 Added NQueens Implementation in Java
  .gitignore
  DSA/.DS_Store
  DSA/algorithms/.DS_Store
  DSA/algorithms/Nqueen/.DS_Store
  DSA/algorithms/Nqueen/java/Queens.java
Labels: hacktoberfest

#14 Add insertion sort in javascript
  DSA/algorithms/Sorting/Javascript/insertion-sort.js
Labels: hacktoberfest

#15 Added Merge Sort
  DSA/algorithms/Sorting/Cpp/mergeSort.cpp
Labels: hacktoberfest

#16 Added Easy problem
  problems/easy/Average.md
Labels: hacktoberfest, questions

#17 FourFunctionCalculator added
  problems/beginner/FourFunctionCalculator.py
Labels: hacktoberfest
